-- Citizen Issue Reporting Platform
-- Sprint 2 / Foundation schema, domain rules, privacy views and RLS.
-- Run this migration only on a new project or through Supabase migration history.

begin;

create schema if not exists extensions;
create extension if not exists pgcrypto;
create extension if not exists postgis schema extensions;

do $$
begin
  create type public.user_role as enum ('citizen', 'official', 'admin');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.report_status as enum (
    'submitted',
    'under_review',
    'assigned',
    'in_progress',
    'resolved',
    'rejected',
    'reopened'
  );
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.report_priority as enum ('low', 'normal', 'high', 'urgent');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.attachment_kind as enum ('evidence', 'resolution');
exception when duplicate_object then null;
end $$;

create table public.departments (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  code text not null unique,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint departments_code_format check (code ~ '^[A-Z0-9_-]{2,12}$'),
  constraint departments_name_length check (char_length(trim(name)) between 2 and 120)
);

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null unique,
  icon_key text not null default 'alert-circle',
  default_sla_hours smallint not null default 48,
  department_id uuid references public.departments(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint categories_sla_range check (default_sla_hours between 1 and 8760),
  constraint categories_name_length check (char_length(trim(name)) between 2 and 80)
);

-- This table extends auth.users. The role is never read from user metadata.
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null default 'Qytetar',
  phone text,
  role public.user_role not null default 'citizen',
  department_id uuid references public.departments(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_email_length check (char_length(email) between 3 and 320),
  constraint profiles_name_length check (char_length(trim(full_name)) between 2 and 120)
);

create table public.reports (
  id uuid primary key default gen_random_uuid(),
  report_number bigint generated by default as identity unique,
  title text not null,
  description text not null,
  category_id uuid not null references public.categories(id) on delete restrict,
  department_id uuid references public.departments(id) on delete set null,
  assigned_official_id uuid references auth.users(id) on delete set null,
  citizen_id uuid not null references auth.users(id) on delete restrict,
  status public.report_status not null default 'submitted',
  priority public.report_priority not null default 'normal',
  location extensions.geography(Point, 4326) not null,
  address_text text,
  sla_due_at timestamptz not null default now(),
  is_public boolean not null default false,
  public_title text,
  public_summary text,
  public_location extensions.geography(Point, 4326),
  resolution_notes text,
  rejected_reason text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reports_title_length check (char_length(trim(title)) between 5 and 160),
  constraint reports_description_length check (char_length(trim(description)) between 10 and 5000),
  constraint reports_public_title_length check (public_title is null or char_length(trim(public_title)) between 5 and 160),
  constraint reports_public_summary_length check (public_summary is null or char_length(trim(public_summary)) between 10 and 1000),
  constraint reports_public_requirements check (
    (is_public = false and public_location is null)
    or (is_public = true and public_location is not null)
  )
);

create table public.report_status_history (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.reports(id) on delete cascade,
  previous_status public.report_status,
  new_status public.report_status not null,
  changed_by uuid references auth.users(id) on delete set null,
  note text,
  created_at timestamptz not null default now(),
  constraint report_status_history_note_length check (note is null or char_length(note) <= 2000)
);

create table public.report_comments (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.reports(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete restrict,
  body text not null,
  is_internal boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint report_comments_body_length check (char_length(trim(body)) between 1 and 2000)
);

create table public.report_attachments (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.reports(id) on delete cascade,
  uploaded_by uuid not null references auth.users(id) on delete restrict,
  bucket_id text not null default 'report-evidence',
  object_path text not null unique,
  kind public.attachment_kind not null default 'evidence',
  mime_type text not null,
  size_bytes integer not null,
  created_at timestamptz not null default now(),
  constraint report_attachments_bucket check (bucket_id = 'report-evidence'),
  constraint report_attachments_mime check (mime_type in ('image/jpeg', 'image/png', 'image/webp')),
  constraint report_attachments_size check (size_bytes between 1 and 10485760),
  constraint report_attachments_path check (object_path ~ '^reports/[0-9a-fA-F-]{36}/[^/]+$')
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references auth.users(id) on delete cascade,
  report_id uuid references public.reports(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  constraint notifications_text_length check (
    char_length(trim(type)) between 2 and 60
    and char_length(trim(title)) between 2 and 160
    and char_length(trim(message)) between 1 and 1000
  )
);

create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint audit_logs_action_length check (char_length(trim(action)) between 2 and 80),
  constraint audit_logs_entity_length check (char_length(trim(entity_type)) between 2 and 80)
);

create index reports_location_gix on public.reports using gist (location);
create index reports_public_location_gix on public.reports using gist (public_location) where is_public = true;
create index reports_citizen_id_idx on public.reports (citizen_id, created_at desc);
create index reports_work_queue_idx on public.reports (status, department_id, priority, created_at desc);
create index reports_sla_idx on public.reports (sla_due_at) where status not in ('resolved', 'rejected');
create index report_status_history_report_idx on public.report_status_history (report_id, created_at);
create index report_comments_report_idx on public.report_comments (report_id, created_at);
create index report_attachments_report_idx on public.report_attachments (report_id, created_at);
create index notifications_recipient_idx on public.notifications (recipient_id, read_at, created_at desc);
create index audit_logs_entity_idx on public.audit_logs (entity_type, entity_id, created_at desc);

create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select p.role from public.profiles p where p.id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() = 'admin', false);
$$;

create or replace function public.is_official_or_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() in ('official', 'admin'), false);
$$;

create or replace function public.can_view_staff_report(
  requested_department_id uuid,
  requested_status public.report_status
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_admin()
    or (
      public.current_user_role() = 'official'
      and (
        requested_department_id = (select p.department_id from public.profiles p where p.id = auth.uid())
        or (requested_department_id is null and requested_status in ('submitted', 'under_review'))
      )
    );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    lower(new.email),
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), 'Qytetar'),
    'citizen'
  )
  on conflict (id) do update
    set email = excluded.email,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of email on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger departments_set_updated_at before update on public.departments
  for each row execute function public.set_updated_at();
create trigger categories_set_updated_at before update on public.categories
  for each row execute function public.set_updated_at();
create trigger profiles_set_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();
create trigger reports_set_updated_at before update on public.reports
  for each row execute function public.set_updated_at();
create trigger comments_set_updated_at before update on public.report_comments
  for each row execute function public.set_updated_at();

create or replace function public.protect_profile_privileged_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() and (
    new.role is distinct from old.role
    or new.department_id is distinct from old.department_id
    or new.email is distinct from old.email
    or new.id is distinct from old.id
  ) then
    raise exception 'Only an administrator can change privileged profile fields';
  end if;
  return new;
end;
$$;

create trigger profiles_protect_privileged_fields before update on public.profiles
  for each row execute function public.protect_profile_privileged_fields();

create or replace function public.prepare_report()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  category_sla smallint;
begin
  select c.default_sla_hours into category_sla
  from public.categories c
  where c.id = new.category_id and c.is_active = true;

  if category_sla is null then
    raise exception 'Category is missing or inactive';
  end if;

  if tg_op = 'INSERT' then
    if new.status <> 'submitted' or new.priority <> 'normal' or new.is_public then
      raise exception 'A new citizen report must start as submitted, normal and private';
    end if;
    new.sla_due_at = now() + make_interval(hours => category_sla);
  end if;

  if new.status = 'resolved' and nullif(trim(new.resolution_notes), '') is null then
    raise exception 'Resolution notes are required before resolving a report';
  end if;

  if new.status = 'rejected' and nullif(trim(new.rejected_reason), '') is null then
    raise exception 'A rejection reason is required';
  end if;

  if new.is_public and new.public_location is null then
    raise exception 'A public report must have a privacy-safe public location';
  end if;

  return new;
end;
$$;

create trigger reports_prepare before insert or update on public.reports
  for each row execute function public.prepare_report();

create or replace function public.validate_report_status_transition()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.status = old.status then
    return new;
  end if;

  if not (
    (old.status = 'submitted' and new.status = 'under_review')
    or (old.status = 'under_review' and new.status in ('assigned', 'rejected'))
    or (old.status = 'assigned' and new.status = 'in_progress')
    or (old.status = 'in_progress' and new.status = 'resolved')
    or (old.status = 'resolved' and new.status = 'reopened')
    or (old.status = 'reopened' and new.status = 'under_review')
  ) then
    raise exception 'Invalid report status transition: % -> %', old.status, new.status;
  end if;

  if new.status = 'resolved' then
    new.resolved_at = coalesce(new.resolved_at, now());
  elsif old.status = 'resolved' and new.status = 'reopened' then
    new.resolved_at = null;
  end if;

  return new;
end;
$$;

create trigger reports_validate_status before update of status on public.reports
  for each row execute function public.validate_report_status_transition();

create or replace function public.record_report_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.report_status_history (report_id, previous_status, new_status, changed_by)
    values (new.id, null, new.status, auth.uid());
  elsif new.status is distinct from old.status then
    insert into public.report_status_history (report_id, previous_status, new_status, changed_by)
    values (new.id, old.status, new.status, auth.uid());
  end if;
  return new;
end;
$$;

create trigger reports_record_status_change after insert or update of status on public.reports
  for each row execute function public.record_report_status_change();

create or replace function public.audit_report_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_logs (actor_id, action, entity_type, entity_id, details)
  values (
    auth.uid(),
    case when tg_op = 'INSERT' then 'report.created' else 'report.updated' end,
    'report',
    new.id,
    jsonb_build_object(
      'report_number', new.report_number,
      'operation', tg_op,
      'status', new.status,
      'department_id', new.department_id,
      'assigned_official_id', new.assigned_official_id,
      'is_public', new.is_public
    )
  );
  return new;
end;
$$;

create trigger reports_audit_change after insert or update on public.reports
  for each row execute function public.audit_report_change();

-- Public views intentionally exclude citizen_id, author_id, email, phone and exact private location.
create or replace view public.public_reports
with (security_barrier = true)
as
select
  r.id,
  r.report_number,
  coalesce(r.public_title, 'Raportim qytetar') as title,
  r.public_summary as summary,
  c.slug as category_slug,
  c.name as category_name,
  r.status,
  r.priority,
  extensions.st_x(r.public_location::extensions.geometry) as longitude,
  extensions.st_y(r.public_location::extensions.geometry) as latitude,
  r.created_at,
  r.updated_at,
  r.resolved_at
from public.reports r
join public.categories c on c.id = r.category_id
where r.is_public = true and r.public_location is not null;

create or replace view public.public_report_comments
with (security_barrier = true)
as
select
  rc.id,
  rc.report_id,
  rc.body,
  case when p.role = 'citizen' then 'Qytetar' else 'Zyrtar komunal' end as author_label,
  rc.created_at
from public.report_comments rc
join public.profiles p on p.id = rc.author_id
where rc.is_internal = false;

create or replace view public.public_report_status_history
with (security_barrier = true)
as
select id, report_id, previous_status, new_status, created_at
from public.report_status_history;

alter table public.departments enable row level security;
alter table public.categories enable row level security;
alter table public.profiles enable row level security;
alter table public.reports enable row level security;
alter table public.report_status_history enable row level security;
alter table public.report_comments enable row level security;
alter table public.report_attachments enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;

create policy departments_public_read on public.departments
  for select to anon, authenticated using (is_active = true or public.is_official_or_admin());
create policy departments_admin_insert on public.departments
  for insert to authenticated with check (public.is_admin());
create policy departments_admin_update on public.departments
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy departments_admin_delete on public.departments
  for delete to authenticated using (public.is_admin());

create policy categories_public_read on public.categories
  for select to anon, authenticated using (is_active = true or public.is_official_or_admin());
create policy categories_admin_insert on public.categories
  for insert to authenticated with check (public.is_admin());
create policy categories_admin_update on public.categories
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy categories_admin_delete on public.categories
  for delete to authenticated using (public.is_admin());

create policy profiles_self_or_staff_read on public.profiles
  for select to authenticated using (id = auth.uid() or public.is_official_or_admin());
create policy profiles_self_update on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

create policy reports_owner_or_staff_read on public.reports
  for select to authenticated using (
    citizen_id = auth.uid()
    or public.can_view_staff_report(department_id, status)
  );
create policy reports_citizen_insert on public.reports
  for insert to authenticated with check (
    citizen_id = auth.uid()
    and status = 'submitted'
    and priority = 'normal'
    and department_id is null
    and assigned_official_id is null
    and is_public = false
    and public_location is null
  );
create policy reports_owner_edit_submitted on public.reports
  for update to authenticated using (citizen_id = auth.uid() and status = 'submitted')
  with check (
    citizen_id = auth.uid()
    and status = 'submitted'
    and is_public = false
    and public_location is null
  );
create policy reports_staff_update on public.reports
  for update to authenticated using (public.can_view_staff_report(department_id, status))
  with check (public.can_view_staff_report(department_id, status) or public.is_admin());

create policy status_history_owner_or_staff_read on public.report_status_history
  for select to authenticated using (
    exists (
      select 1 from public.reports r
      where r.id = report_status_history.report_id
        and (r.citizen_id = auth.uid() or public.can_view_staff_report(r.department_id, r.status))
    )
  );

create policy comments_owner_or_staff_read on public.report_comments
  for select to authenticated using (
    author_id = auth.uid()
    or public.is_official_or_admin()
    or (
      is_internal = false
      and exists (select 1 from public.reports r where r.id = report_comments.report_id and r.citizen_id = auth.uid())
    )
  );
create policy comments_authenticated_insert on public.report_comments
  for insert to authenticated with check (
    author_id = auth.uid()
    and (
      public.is_official_or_admin()
      or (
        is_internal = false
        and exists (select 1 from public.reports r where r.id = report_comments.report_id and r.citizen_id = auth.uid())
      )
    )
  );

create policy attachments_owner_or_staff_read on public.report_attachments
  for select to authenticated using (
    uploaded_by = auth.uid()
    or public.is_official_or_admin()
    or exists (select 1 from public.reports r where r.id = report_attachments.report_id and r.citizen_id = auth.uid())
  );
create policy attachments_owner_or_staff_insert on public.report_attachments
  for insert to authenticated with check (
    uploaded_by = auth.uid()
    and (
      public.is_official_or_admin()
      or exists (select 1 from public.reports r where r.id = report_attachments.report_id and r.citizen_id = auth.uid())
    )
  );

create policy notifications_owner_read on public.notifications
  for select to authenticated using (recipient_id = auth.uid());
create policy notifications_owner_update on public.notifications
  for update to authenticated using (recipient_id = auth.uid()) with check (recipient_id = auth.uid());

create policy audit_logs_admin_read on public.audit_logs
  for select to authenticated using (public.is_admin());

revoke all on table public.profiles, public.reports, public.report_status_history,
  public.report_comments, public.report_attachments, public.notifications, public.audit_logs
  from anon;
grant select on table public.departments, public.categories to anon, authenticated;
grant select, insert, update on table public.profiles, public.reports, public.report_comments,
  public.report_attachments, public.notifications to authenticated;
grant select on table public.report_status_history, public.audit_logs to authenticated;
grant select on table public.public_reports, public.public_report_comments,
  public.public_report_status_history to anon, authenticated;
revoke all on table public.public_reports, public.public_report_comments,
  public.public_report_status_history from public;
grant select on table public.public_reports, public.public_report_comments,
  public.public_report_status_history to anon, authenticated;

revoke execute on function public.current_user_role() from public;
revoke execute on function public.is_admin() from public;
revoke execute on function public.is_official_or_admin() from public;
revoke execute on function public.can_view_staff_report(uuid, public.report_status) from public;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_official_or_admin() to authenticated;
grant execute on function public.can_view_staff_report(uuid, public.report_status) to authenticated;

commit;
